### PR TITLE
Add a message prefix to avoid plugin confusion

### PR DESCRIPTION
**Pull request by garbagemule**
Due to BattleArena's selfish and obtrusive sign handling, it is not
possible to place signs where the first line of the sign contains
a name of a BattleArena class without BattleArena interfering. With
this and the fact that both MobArena and BattleArena have a default
class called Archer, MobArena users very frequently complain that
either "only the Archer sign activates" (because BattleArena steals
the sign) or "the only class that doesn't work is Archer" (because
BattleArena manipulates the contents of the sign).

This commit adds a message prefix to the MessageUtil class so all
messages from BattleArena are prefixed with [BattleArena]. Changing
this prefix is very easy and could easily be made customizable. It
does, however, prevent any confusion as to which plugin the message
comes from.

### CODE REVIEW

**Comment by garbagemule** [comment]
Alternative solution: https://github.com/alkarinv/BattleArena/pull/184

**Comment by it-split** [comment]
I support this. I recently had an issue where I was mistaking the class sign being made by Battlearena as the class-sign from another plugin. This caused lots of confusion, and I had to trouble others who had the same issue to help fix it.

**Comment by garbagemule** [comment]
@alkarinv Any kind of response would be greatly appreciated. We just had another user in the MobArena channel complain that "only the archer sign works". I'd like to know if I should keep telling the users to try to nag you guys about this, or if there's any type of resolution in the works. I really don't think it's too much to ask that BattleArena changes to a less selfish and obtrusive sign registration. In case you don't wish to change any of this behavior, could you at least consider renaming your default Archer class to "Ranger" or something similar so the classes of the plugins are disjoint name sets?

**Comment by alkarinv** [comment]
Hey Garbage, Sorry I dont know how I completely missed this thread.  I got busy for a while and this went right by me.

Also thanks for the code, I actually just changed it so I unfortunately can't use this pull, but I will be releasing the version with the sign fix today.  So within 3-4 days there shouldn't be a conflict anymore.

**Comment by garbagemule** [comment]
alkarinv.send(Math.pow(♥, 99));

**Pull request closed without merging**
