### PR TITLE
Update src/mc/alk/arena/util/TeamUtil.java

### PR DESCRIPTION
**Pull request by netherfoam**
NPE on gameover if a player was dead

### CODE REVIEW

**Comment by netherfoam** [comment]
Hey, I want to compile your plugin from the source, but I can't find MassDisguise.jar.  Wherebouts can I get it?

**Comment by netherfoam** [comment]
Also need VirtualPlayers & PluginUpdater, I think?

**Comment by alkarinv** [comment]
MassDisguise is no longer being updated... so I'll just take out that dependency.
I just made PluginUpdater, I'll put the code up on github for you.  I haven't really tested it thoroughly yet, which is why I haven't activated it as a default yet.  I know it works on linux/mac, but windows it won't work.

**Comment by netherfoam** [comment]
Just got VirtualPlayers from your github :)

Thanks ^_^

**Pull request merged**
